"""Identity domain persistence models.

Represents platform users, DISCOM-facing utility account metadata, and consent
records (docs/04_DATA_MODEL.md sections 1, 2, 9).

Phase-1 scope only. No market, telemetry or settlement columns here.

NOTE: A Phase-1 Alembic migration must be generated by Yagnik before these
tables exist in the database:
    make revision m="phase1 identity and asset tables"
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import TYPE_CHECKING

from sqlalchemy import DateTime, ForeignKey, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.db.models.assets import Site


class User(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    """Platform identity (docs/04_DATA_MODEL.md section 1).

    `email` is nullable to support demo/anonymous modes. `role` and `status`
    use string columns validated at the application layer (Pydantic enums) so
    adding a new role in a later phase does not require a DDL migration.
    """

    __tablename__ = "users"

    email: Mapped[str | None] = mapped_column(String(320), unique=True, nullable=True)
    display_name: Mapped[str] = mapped_column(String(200), nullable=False)
    # role values: consumer | prosumer | operator | regulator_viewer | admin
    role: Mapped[str] = mapped_column(String(32), nullable=False, default="consumer")
    # status values: active | suspended | pending
    status: Mapped[str] = mapped_column(String(32), nullable=False, default="active")

    # relationships
    utility_accounts: Mapped[list[UtilityAccount]] = relationship(
        "UtilityAccount", back_populates="user", cascade="all, delete-orphan"
    )
    sites: Mapped[list[Site]] = relationship(  # noqa: F821 – forward ref resolved at runtime
        "Site", back_populates="owner", cascade="all, delete-orphan"
    )
    consents: Mapped[list[Consent]] = relationship(
        "Consent", back_populates="user", cascade="all, delete-orphan"
    )

    def __repr__(self) -> str:  # pragma: no cover
        return f"<User id={self.id} role={self.role!r} email={self.email!r}>"


class UtilityAccount(UUIDPrimaryKeyMixin, Base):
    """DISCOM-facing identity metadata (docs/04_DATA_MODEL.md section 2).

    Raw consumer numbers must never be stored; only the SHA-256 hash is
    persisted (docs/00_PROJECT_BIBLE.md section 8).
    """

    __tablename__ = "utility_accounts"

    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    discom_code: Mapped[str] = mapped_column(String(64), nullable=False)
    # SHA-256 hex digest of the raw consumer number — never the raw value.
    consumer_number_hash: Mapped[str | None] = mapped_column(String(64), nullable=True)
    # verification_level values: none | basic | kyc | verified
    verification_level: Mapped[str] = mapped_column(
        String(32), nullable=False, default="none"
    )
    verified_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    user: Mapped[User] = relationship("User", back_populates="utility_accounts")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<UtilityAccount id={self.id} discom={self.discom_code!r}>"


class Consent(UUIDPrimaryKeyMixin, Base):
    """Consent trail for device/meter data sharing (docs/04_DATA_MODEL.md section 9)."""

    __tablename__ = "consents"

    user_id: Mapped[uuid.UUID] = mapped_column(
        Uuid(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    scope: Mapped[str] = mapped_column(String(128), nullable=False)
    granted_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(
        DateTime(timezone=True), nullable=True
    )

    user: Mapped[User] = relationship("User", back_populates="consents")

    def __repr__(self) -> str:  # pragma: no cover
        return f"<Consent id={self.id} scope={self.scope!r}>"


# Resolve forward reference from User → Site (Site is in assets.py)
# We import here *after* Site is defined to avoid a circular import at
# definition time. The relationship string "Site" works with SQLAlchemy's
# lazy mapper resolution; no explicit import is needed at module level.
