"""phase 5 grid snapshots and validation runs

Revision ID: fe9244997fc2
Revises: 0005_market_orders_trades
Create Date: 2026-09-12 17:56:56.449813
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0006_grid_validation"
down_revision: str | None = "0005_market_orders_trades"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


grid_validation_decision = _enum(
    "grid_validation_decision", "accept", "reprice", "reduce", "shift", "reject"
)
grid_validation_status = _enum("grid_validation_status", "safe", "unsafe", "unknown")

ALL_ENUMS = (grid_validation_decision, grid_validation_status)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "grid_snapshots",
        sa.Column("feeder_id", sa.String(length=64), nullable=True),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("system_load_kw", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("generation_kw", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("transformer_loading_pct", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("max_line_loading_pct", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("min_voltage_pu", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("max_voltage_pu", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_line_loading_pct IS NULL OR max_line_loading_pct >= 0",
            name=op.f("ck_grid_snapshots_line_loading_not_negative"),
        ),
        sa.CheckConstraint(
            "max_voltage_pu IS NULL OR max_voltage_pu >= 0",
            name=op.f("ck_grid_snapshots_max_voltage_not_negative"),
        ),
        sa.CheckConstraint(
            "min_voltage_pu IS NULL OR max_voltage_pu IS NULL OR min_voltage_pu <= max_voltage_pu",
            name=op.f("ck_grid_snapshots_voltage_range_ordered"),
        ),
        sa.CheckConstraint(
            "min_voltage_pu IS NULL OR min_voltage_pu >= 0",
            name=op.f("ck_grid_snapshots_min_voltage_not_negative"),
        ),
        sa.CheckConstraint(
            "transformer_loading_pct IS NULL OR transformer_loading_pct >= 0",
            name=op.f("ck_grid_snapshots_transformer_loading_not_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grid_snapshots")),
    )
    op.create_index(
        "ix_grid_snapshots_feeder_id_captured_at",
        "grid_snapshots",
        ["feeder_id", "captured_at"],
        unique=False,
    )
    op.create_table(
        "grid_validation_runs",
        sa.Column("trade_id", sa.Uuid(), nullable=True),
        sa.Column("grid_snapshot_id", sa.Uuid(), nullable=True),
        sa.Column("simulation_engine", sa.String(length=64), nullable=False),
        sa.Column("engine_version", sa.String(length=64), nullable=True),
        sa.Column("input_hash", sa.String(length=64), nullable=False),
        sa.Column("status", grid_validation_status, nullable=False),
        sa.Column("min_voltage_pu", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("max_voltage_pu", sa.Numeric(precision=8, scale=4), nullable=True),
        sa.Column("max_line_loading_pct", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column("max_transformer_loading_pct", sa.Numeric(precision=8, scale=3), nullable=True),
        sa.Column(
            "decision",
            grid_validation_decision,
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(status = 'safe' AND decision = 'accept') "
            "OR (status <> 'safe' AND decision <> 'accept')",
            name=op.f("ck_grid_validation_runs_decision_agrees_with_safety"),
        ),
        sa.CheckConstraint(
            "min_voltage_pu IS NULL OR max_voltage_pu IS NULL OR min_voltage_pu <= max_voltage_pu",
            name=op.f("ck_grid_validation_runs_voltage_range_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["grid_snapshot_id"],
            ["grid_snapshots.id"],
            name=op.f("fk_grid_validation_runs_grid_snapshot_id_grid_snapshots"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_grid_validation_runs")),
    )
    op.create_index(
        "ix_grid_validation_runs_decision", "grid_validation_runs", ["decision"], unique=False
    )
    op.create_index(
        "ix_grid_validation_runs_grid_snapshot_id",
        "grid_validation_runs",
        ["grid_snapshot_id"],
        unique=False,
    )
    op.create_index(
        "ix_grid_validation_runs_input_hash", "grid_validation_runs", ["input_hash"], unique=False
    )
    op.create_index(
        "ix_grid_validation_runs_trade_id", "grid_validation_runs", ["trade_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_grid_validation_runs_trade_id", table_name="grid_validation_runs")
    op.drop_index("ix_grid_validation_runs_input_hash", table_name="grid_validation_runs")
    op.drop_index("ix_grid_validation_runs_grid_snapshot_id", table_name="grid_validation_runs")
    op.drop_index("ix_grid_validation_runs_decision", table_name="grid_validation_runs")
    op.drop_table("grid_validation_runs")
    op.drop_index("ix_grid_snapshots_feeder_id_captured_at", table_name="grid_snapshots")
    op.drop_table("grid_snapshots")
    # ### end Alembic commands ###

    # The tables are gone; the types they used are not.
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
