"""phase 7 settlement and reconciliation

Creates docs/04_DATA_MODEL.md entities 19 and 20 — the committed-versus-actual
comparison and the final financial allocation.

Two tables rather than one: a reconciliation exists even when delivery could
not be measured, while a settlement exists only once it can be.

Columns are exactly the fields the data model lists. The effective price is not
stored — it is recoverable as `gross_amount_inr / settled_kwh` and reachable
through `price_components` for the trade.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0010_settlement"
down_revision: str | None = "0009_price_components"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


reconciliation_status = _enum("reconciliation_status", "awaiting_telemetry", "reconciled")
settlement_status = _enum("settlement_status", "pending", "settled", "superseded")

ALL_ENUMS = (reconciliation_status, settlement_status)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "meter_reconciliations",
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("committed_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("actual_kwh", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("deviation_kwh", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("within_tolerance", sa.Boolean(), nullable=False),
        sa.Column("balancing_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("reconciliation_status", reconciliation_status, nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(actual_kwh IS NOT NULL AND deviation_kwh IS NOT NULL) "
            "OR (actual_kwh IS NULL AND deviation_kwh IS NULL AND NOT within_tolerance)",
            name=op.f("ck_meter_reconciliations_measurement_agrees_with_verdict"),
        ),
        sa.CheckConstraint(
            "actual_kwh IS NULL OR actual_kwh >= 0",
            name=op.f("ck_meter_reconciliations_actual_not_negative"),
        ),
        sa.CheckConstraint(
            "balancing_kwh >= 0", name=op.f("ck_meter_reconciliations_balancing_not_negative")
        ),
        sa.CheckConstraint(
            "committed_kwh > 0", name=op.f("ck_meter_reconciliations_committed_positive")
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_meter_reconciliations_trade_id_trades"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_meter_reconciliations")),
    )
    op.create_index(
        "ix_meter_reconciliations_status",
        "meter_reconciliations",
        ["reconciliation_status"],
        unique=False,
    )
    op.create_index(
        "ix_meter_reconciliations_trade_id", "meter_reconciliations", ["trade_id"], unique=False
    )
    op.create_table(
        "settlements",
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("buyer_user_id", sa.Uuid(), nullable=False),
        sa.Column("seller_user_id", sa.Uuid(), nullable=False),
        sa.Column("settled_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("gross_amount_inr", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("platform_fee_inr", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("balancing_charge_inr", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("seller_credit_inr", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("buyer_debit_inr", sa.Numeric(precision=16, scale=2), nullable=False),
        sa.Column("status", settlement_status, nullable=False),
        sa.Column("settled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "balancing_charge_inr >= 0", name=op.f("ck_settlements_balancing_charge_not_negative")
        ),
        sa.CheckConstraint(
            "buyer_debit_inr = seller_credit_inr + platform_fee_inr + balancing_charge_inr",
            name=op.f("ck_settlements_ledger_balances"),
        ),
        sa.CheckConstraint(
            "buyer_debit_inr >= 0", name=op.f("ck_settlements_buyer_debit_not_negative")
        ),
        sa.CheckConstraint("gross_amount_inr >= 0", name=op.f("ck_settlements_gross_not_negative")),
        sa.CheckConstraint(
            "platform_fee_inr >= 0", name=op.f("ck_settlements_platform_fee_not_negative")
        ),
        sa.CheckConstraint("settled_kwh >= 0", name=op.f("ck_settlements_settled_not_negative")),
        sa.ForeignKeyConstraint(
            ["buyer_user_id"],
            ["users.id"],
            name=op.f("fk_settlements_buyer_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["seller_user_id"],
            ["users.id"],
            name=op.f("fk_settlements_seller_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_settlements_trade_id_trades"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settlements")),
    )
    op.create_index("ix_settlements_buyer_user_id", "settlements", ["buyer_user_id"], unique=False)
    op.create_index(
        "ix_settlements_seller_user_id", "settlements", ["seller_user_id"], unique=False
    )
    op.create_index("ix_settlements_status", "settlements", ["status"], unique=False)
    op.create_index("ix_settlements_trade_id", "settlements", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_settlements_trade_id", table_name="settlements")
    op.drop_index("ix_settlements_status", table_name="settlements")
    op.drop_index("ix_settlements_seller_user_id", table_name="settlements")
    op.drop_index("ix_settlements_buyer_user_id", table_name="settlements")
    op.drop_table("settlements")
    op.drop_index("ix_meter_reconciliations_trade_id", table_name="meter_reconciliations")
    op.drop_index("ix_meter_reconciliations_status", table_name="meter_reconciliations")
    op.drop_table("meter_reconciliations")
    # ### end Alembic commands ###

    # The tables are gone; the types they used are not.
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
