"""phase 6 price components

Creates docs/04_DATA_MODEL.md entity 18 — the explainable price calculation.

Columns are exactly the fields the data model lists; nothing is added. The grid
state and the forecast a price rested on are already reachable through
`trades.grid_validation_id` and `orders.forecast_basis_id`.

No enum type is created. `PriceComponentKind` and `TimeOfDayBand` are domain
vocabularies used to explain a calculation, not stored values: this table holds
one column per component rather than one row per component.

Revision ID: 0009_price_components
Revises: 0008_trade_grid_validation_fk
Create Date: 2026-09-12 19:04:00.420120
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0009_price_components"
down_revision: str | None = "0008_trade_grid_validation_fk"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "price_components",
        sa.Column("trade_id", sa.Uuid(), nullable=False),
        sa.Column("base_market_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("time_component", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("congestion_component", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("imbalance_component", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("local_renewable_component", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("final_price", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("formula_version", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "base_market_price + time_component + congestion_component "
            "+ imbalance_component + local_renewable_component = final_price",
            name=op.f("ck_price_components_components_sum_to_final_price"),
        ),
        sa.CheckConstraint(
            "base_market_price >= 0", name=op.f("ck_price_components_base_price_not_negative")
        ),
        sa.CheckConstraint(
            "congestion_component >= 0", name=op.f("ck_price_components_congestion_is_a_charge")
        ),
        sa.CheckConstraint(
            "final_price >= 0", name=op.f("ck_price_components_final_price_not_negative")
        ),
        sa.CheckConstraint(
            "imbalance_component >= 0", name=op.f("ck_price_components_imbalance_is_a_charge")
        ),
        sa.CheckConstraint(
            "local_renewable_component <= 0",
            name=op.f("ck_price_components_local_renewable_is_an_incentive"),
        ),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
            name=op.f("fk_price_components_trade_id_trades"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_price_components")),
    )
    op.create_index("ix_price_components_trade_id", "price_components", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_price_components_trade_id", table_name="price_components")
    op.drop_table("price_components")
    # ### end Alembic commands ###
