"""phase 4 market sessions orders trades

Revision ID: d05284b21e54
Revises: 0004_forecast_runs_and_points
Create Date: 2026-09-12 17:18:40.869754
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0005_market_orders_trades"
down_revision: str | None = "0004_forecast_runs_and_points"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


market_type = _enum("market_type", "day_ahead")
market_session_status = _enum("market_session_status", "open", "closed", "cleared")
order_side = _enum("order_side", "buy", "sell")
order_status = _enum("order_status", "open", "partially_filled", "filled", "cancelled", "rejected")
trade_status = _enum("trade_status", "proposed")

ALL_ENUMS = (
    market_type,
    market_session_status,
    order_side,
    order_status,
    trade_status,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "market_sessions",
        sa.Column("market_date", sa.Date(), nullable=False),
        sa.Column("market_type", market_type, server_default="day_ahead", nullable=False),
        sa.Column("status", market_session_status, server_default="open", nullable=False),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("cleared_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "cleared_at IS NULL OR closed_at IS NULL OR cleared_at >= closed_at",
            name=op.f("ck_market_sessions_cleared_after_closed"),
        ),
        sa.CheckConstraint(
            "closed_at IS NULL OR opened_at IS NULL OR closed_at >= opened_at",
            name=op.f("ck_market_sessions_closed_after_opened"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_market_sessions")),
        sa.UniqueConstraint(
            "market_date", "market_type", name="uq_market_sessions_market_date_market_type"
        ),
    )
    op.create_index(
        "ix_market_sessions_market_date", "market_sessions", ["market_date"], unique=False
    )
    op.create_index("ix_market_sessions_status", "market_sessions", ["status"], unique=False)
    op.create_table(
        "orders",
        sa.Column("market_session_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("node_id", sa.Uuid(), nullable=True),
        sa.Column("side", order_side, nullable=False),
        sa.Column("energy_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("min_price_inr_per_kwh", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("max_price_inr_per_kwh", sa.Numeric(precision=12, scale=4), nullable=True),
        sa.Column("delivery_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("forecast_basis_id", sa.Uuid(), nullable=True),
        sa.Column("reliability_score_snapshot", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("status", order_status, server_default="open", nullable=False),
        sa.Column(
            "matched_kwh", sa.Numeric(precision=14, scale=4), server_default="0", nullable=False
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "(side <> 'buy') OR (max_price_inr_per_kwh IS NOT NULL)",
            name=op.f("ck_orders_buy_requires_max_price"),
        ),
        sa.CheckConstraint(
            "(side <> 'sell') OR (min_price_inr_per_kwh IS NOT NULL)",
            name=op.f("ck_orders_sell_requires_min_price"),
        ),
        sa.CheckConstraint(
            "delivery_end > delivery_start", name=op.f("ck_orders_delivery_end_after_start")
        ),
        sa.CheckConstraint("energy_kwh > 0", name=op.f("ck_orders_energy_positive")),
        sa.CheckConstraint(
            "matched_kwh >= 0 AND matched_kwh <= energy_kwh",
            name=op.f("ck_orders_matched_within_energy"),
        ),
        sa.CheckConstraint(
            "max_price_inr_per_kwh IS NULL OR max_price_inr_per_kwh >= 0",
            name=op.f("ck_orders_max_price_not_negative"),
        ),
        sa.CheckConstraint(
            "min_price_inr_per_kwh IS NULL OR min_price_inr_per_kwh >= 0",
            name=op.f("ck_orders_min_price_not_negative"),
        ),
        sa.CheckConstraint(
            "reliability_score_snapshot IS NULL OR reliability_score_snapshot BETWEEN 0 AND 1",
            name=op.f("ck_orders_reliability_score_is_a_ratio"),
        ),
        sa.ForeignKeyConstraint(
            ["forecast_basis_id"],
            ["forecast_runs.id"],
            name=op.f("fk_orders_forecast_basis_id_forecast_runs"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["market_session_id"],
            ["market_sessions.id"],
            name=op.f("fk_orders_market_session_id_market_sessions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["node_id"],
            ["grid_nodes.id"],
            name=op.f("fk_orders_node_id_grid_nodes"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"], ["sites.id"], name=op.f("fk_orders_site_id_sites"), ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_orders_user_id_users"), ondelete="RESTRICT"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_orders")),
    )
    op.create_index("ix_orders_forecast_basis_id", "orders", ["forecast_basis_id"], unique=False)
    op.create_index(
        "ix_orders_market_session_id_side_status",
        "orders",
        ["market_session_id", "side", "status"],
        unique=False,
    )
    op.create_index("ix_orders_node_id", "orders", ["node_id"], unique=False)
    op.create_index("ix_orders_site_id", "orders", ["site_id"], unique=False)
    op.create_index("ix_orders_user_id", "orders", ["user_id"], unique=False)
    op.create_table(
        "trades",
        sa.Column("buy_order_id", sa.Uuid(), nullable=False),
        sa.Column("sell_order_id", sa.Uuid(), nullable=False),
        sa.Column("quantity_kwh", sa.Numeric(precision=14, scale=4), nullable=False),
        sa.Column("clearing_price_inr_per_kwh", sa.Numeric(precision=12, scale=4), nullable=False),
        sa.Column("delivery_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("delivery_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("grid_validation_id", sa.Uuid(), nullable=True),
        sa.Column("status", trade_status, server_default="proposed", nullable=False),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("matching_engine", sa.String(length=64), nullable=True),
        sa.Column("matching_engine_version", sa.String(length=64), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("buy_order_id <> sell_order_id", name=op.f("ck_trades_distinct_orders")),
        sa.CheckConstraint(
            "clearing_price_inr_per_kwh >= 0", name=op.f("ck_trades_clearing_price_not_negative")
        ),
        sa.CheckConstraint(
            "delivery_end > delivery_start", name=op.f("ck_trades_delivery_end_after_start")
        ),
        sa.CheckConstraint("quantity_kwh > 0", name=op.f("ck_trades_quantity_positive")),
        sa.ForeignKeyConstraint(
            ["buy_order_id"],
            ["orders.id"],
            name=op.f("fk_trades_buy_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["sell_order_id"],
            ["orders.id"],
            name=op.f("fk_trades_sell_order_id_orders"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_trades")),
        sa.UniqueConstraint(
            "buy_order_id",
            "sell_order_id",
            "delivery_start",
            name="uq_trades_buy_order_id_sell_order_id_delivery_start",
        ),
    )
    op.create_index("ix_trades_buy_order_id", "trades", ["buy_order_id"], unique=False)
    op.create_index("ix_trades_sell_order_id", "trades", ["sell_order_id"], unique=False)
    op.create_index("ix_trades_status", "trades", ["status"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_trades_status", table_name="trades")
    op.drop_index("ix_trades_sell_order_id", table_name="trades")
    op.drop_index("ix_trades_buy_order_id", table_name="trades")
    op.drop_table("trades")
    op.drop_index("ix_orders_user_id", table_name="orders")
    op.drop_index("ix_orders_site_id", table_name="orders")
    op.drop_index("ix_orders_node_id", table_name="orders")
    op.drop_index("ix_orders_market_session_id_side_status", table_name="orders")
    op.drop_index("ix_orders_forecast_basis_id", table_name="orders")
    op.drop_table("orders")
    op.drop_index("ix_market_sessions_status", table_name="market_sessions")
    op.drop_index("ix_market_sessions_market_date", table_name="market_sessions")
    op.drop_table("market_sessions")
    # ### end Alembic commands ###

    # The tables are gone; the types they used are not.
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
