"""phase 8 audit events

Creates docs/04_DATA_MODEL.md entity 21 — the append-only, hash-chained record
of material business events.

`recorded_at` is the one column beyond entity 21's field list. Every other
table gets an append timestamp from `TimestampMixin`; this table cannot use the
mixin, because an `updated_at` column would advertise a mutability an audit
ledger must not have. It is hashed along with `event_time`.

Two unique constraints make the chain a line rather than a tree: one hash may
exist once, and one predecessor may be claimed once — with NULLS NOT DISTINCT,
so "no predecessor" is claimable only once and the genesis event is unique.

No ledger, network or blockchain is involved. PostgreSQL is the audit source of
truth (docs/06_OPEN_SOURCE_INTEGRATION.md section 6).
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0011_audit_events"
down_revision: str | None = "0010_settlement"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


audit_event_type = _enum(
    "audit_event_type",
    "order_placed",
    "market_cleared",
    "trade_proposed",
    "grid_validation_recorded",
    "price_calculated",
    "trade_reconciled",
    "trade_settled",
)
audit_entity_type = _enum("audit_entity_type", "order", "trade", "market_session")

ALL_ENUMS = (audit_event_type, audit_entity_type)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("event_type", audit_event_type, nullable=False),
        sa.Column("entity_type", audit_entity_type, nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("event_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=True),
        sa.Column("payload_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_hash", sa.String(length=64), nullable=False),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("ledger_anchor_id", sa.String(length=200), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.CheckConstraint(
            "event_hash <> previous_hash", name=op.f("ck_audit_events_event_does_not_follow_itself")
        ),
        sa.CheckConstraint(
            "length(event_hash) = 64", name=op.f("ck_audit_events_event_hash_is_sha256")
        ),
        sa.CheckConstraint(
            "previous_hash IS NULL OR length(previous_hash) = 64",
            name=op.f("ck_audit_events_previous_hash_is_sha256"),
        ),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
        sa.UniqueConstraint("event_hash", name="uq_audit_events_event_hash"),
        sa.UniqueConstraint(
            "previous_hash",
            name="uq_audit_events_previous_hash",
            postgresql_nulls_not_distinct=True,
        ),
    )
    op.create_index(
        "ix_audit_events_entity_type_entity_id",
        "audit_events",
        ["entity_type", "entity_id"],
        unique=False,
    )
    op.create_index("ix_audit_events_event_type", "audit_events", ["event_type"], unique=False)
    op.create_index("ix_audit_events_recorded_at", "audit_events", ["recorded_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_audit_events_recorded_at", table_name="audit_events")
    op.drop_index("ix_audit_events_event_type", table_name="audit_events")
    op.drop_index("ix_audit_events_entity_type_entity_id", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###

    # The table is gone; the types it used are not.
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
