"""phase 3 forecast runs and points

Revision ID: fb71a22b6fce
Revises: 0003_telemetry_readings
Create Date: 2026-09-12 16:38:11.716987
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0004_forecast_runs_and_points"
down_revision: str | None = "0003_telemetry_readings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def _enum(name: str, *values: str) -> postgresql.ENUM:
    return postgresql.ENUM(*values, name=name, create_type=False)


forecast_type = _enum("forecast_type", "solar", "load", "surplus")
forecast_run_status = _enum("forecast_run_status", "pending", "running", "completed", "failed")

ALL_ENUMS = (forecast_type, forecast_run_status)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in ALL_ENUMS:
        enum_type.create(bind, checkfirst=True)
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "forecast_runs",
        sa.Column("forecast_type", forecast_type, nullable=False),
        sa.Column("provider", sa.String(length=64), nullable=False),
        sa.Column("model_version", sa.String(length=64), nullable=False),
        sa.Column("horizon_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("horizon_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", forecast_run_status, server_default="pending", nullable=False),
        sa.Column("error", sa.String(length=500), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "horizon_end > horizon_start", name=op.f("ck_forecast_runs_horizon_end_after_start")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_runs")),
    )
    op.create_index(
        "ix_forecast_runs_forecast_type_horizon_start",
        "forecast_runs",
        ["forecast_type", "horizon_start"],
        unique=False,
    )
    op.create_index("ix_forecast_runs_status", "forecast_runs", ["status"], unique=False)
    op.create_table(
        "forecast_points",
        sa.Column("forecast_run_id", sa.Uuid(), nullable=False),
        sa.Column("site_id", sa.Uuid(), nullable=False),
        sa.Column("interval_start", sa.DateTime(timezone=True), nullable=False),
        sa.Column("interval_end", sa.DateTime(timezone=True), nullable=False),
        sa.Column("predicted_kw", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("predicted_kwh", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("confidence", sa.Numeric(precision=5, scale=4), nullable=True),
        sa.Column("lower_bound", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("upper_bound", sa.Numeric(precision=14, scale=4), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "confidence IS NULL OR confidence BETWEEN 0 AND 1",
            name=op.f("ck_forecast_points_confidence_is_a_probability"),
        ),
        sa.CheckConstraint(
            "interval_end > interval_start",
            name=op.f("ck_forecast_points_interval_end_after_start"),
        ),
        sa.CheckConstraint(
            "lower_bound IS NULL OR upper_bound IS NULL OR lower_bound <= upper_bound",
            name=op.f("ck_forecast_points_bounds_ordered"),
        ),
        sa.ForeignKeyConstraint(
            ["forecast_run_id"],
            ["forecast_runs.id"],
            name=op.f("fk_forecast_points_forecast_run_id_forecast_runs"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["site_id"],
            ["sites.id"],
            name=op.f("fk_forecast_points_site_id_sites"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_points")),
        sa.UniqueConstraint(
            "forecast_run_id",
            "site_id",
            "interval_start",
            name="uq_forecast_points_forecast_run_id_site_id_interval_start",
        ),
    )
    op.create_index(
        "ix_forecast_points_forecast_run_id", "forecast_points", ["forecast_run_id"], unique=False
    )
    op.create_index(
        "ix_forecast_points_site_id_interval_start",
        "forecast_points",
        ["site_id", "interval_start"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_forecast_points_site_id_interval_start", table_name="forecast_points")
    op.drop_index("ix_forecast_points_forecast_run_id", table_name="forecast_points")
    op.drop_table("forecast_points")
    op.drop_index("ix_forecast_runs_status", table_name="forecast_runs")
    op.drop_index("ix_forecast_runs_forecast_type_horizon_start", table_name="forecast_runs")
    op.drop_table("forecast_runs")
    # ### end Alembic commands ###

    # The tables are gone; the types they used are not.
    bind = op.get_bind()
    for enum_type in reversed(ALL_ENUMS):
        enum_type.drop(bind, checkfirst=True)
